[build]
  functions = "functions"
  command = "npm run build"

[functions]
  included_files = ["./assets/compareBalls/**", "./assets/compareBallsDD/**"]
  timeout = "60"

[build.environment]
  NODE_VERSION = "20"